


def fibonacci_seq(x0,x1):
    '''
    fibonacci seq is a generator yielding the members of the fibonacci
    sequence generated by starting numbers x0, x1.
    '''
    a, b = x0, x1
    yield a
    yield b
    while True:
        a, b = b, a + b
        yield b

        
